### PR TITLE
Move to use wl-pprint-extras internally

### PR DESCRIPTION
**Pull request by nwf**
Make ansified Docs a wrapper around a beefed up wl-pprint-extras.
This depends on github pull request #11 thereof.

### CODE REVIEW

**Comment by hvr** [comment]
One thing to consider is that this will pull in additional build-deps

**Comment by nwf** [comment]
Is that a problem for any existing ansi-wl-pprint user?  As someone who has "the other" problem (I have code that uses wl-pprint-extras and, thanks to using trifecta, also ansi-wl-pprint) it's a pain to have to have both pretty-printers in scope for certain modules.

**Comment by ekmett** [comment]
I've pretty much resolved to do fairly minimal refactoring when it comes to maintaining this package. I'd prefer to keep it more or less intact. It has a very wide array of users already and sits very low in the dependency graph of other packages.

I have, however, resolved to doing a fair bit of refactoring on `wl-pprint-extras` to help support others who want to use it to replace `annotated-wl-pprint`. Notably adding a parameter to wl-pprint-extras for 'surrounding' things was requested by both you and at the Haskell Implementor's Workshop by @david-christiansen.

I understand your frustration at maintaining instances for both packages, but I confess I'm more concerned about backlash in the other direction than twice as many instances. Especially when the instance story for `wl-pprint-extras` isn't actually all that good.

**Comment by david-christiansen** [comment]
Being able to replace annotated-wl-pprint with wl-pprint-extras and eliminate a library from maintenance would be very nice :)

**Comment by nwf** [comment]
Hm.  Just selfishly considering my own code, could I persuade you @ekmett to break the version of ansi-wl-pprint created by this patch out into its own library (wl-pprint-extras-ansi?) and move trifecta to using it?  Are there any depends of wl-pprint-extras that are not already depends of trifecta?  (Casually, the obvious candidates from the cabal files are nats, semigroupoids, and text, but: trifecta depends on parsers which depends on text and trifecta depends on lens which depends on nats and semigroupoids; did I miss anything?)

The problem, from my perspective, is not that I have to maintain multiple instances, but rather that various parts of my code return either ansi-wl-pprint Doc or wl-pprint-extra Doc and if I want to slap a header on them or similar I have to have both pretty printers qualified in scope.  It's not a very high maintenance burden, just a bit more of a pain than I would like.

**Comment by ekmett** [comment]
@nwf Well, another option would be to resurrect `wl-pprint-terminfo`. This is what we used to use. Updated with support for surrounding tags a la @david-christiansen's `annotated-wl-pprint` that would seem to give you what you want.

As for the fate of `trifecta`'s pretty printing, we switched to `ansi-wl-pprint` deliberately, because it was already a dependency, so we'd need to get a lot out of the exchange. 

I am somewhat inclined to switch trifecta over to something using a form of `wl-pprint-extra`-based that has support for surrounding tags if we can do so in a way that Idris and other users like you can take advantage of it nicely, but I'm also sliced a bit thinly at the moment and haven't thought fully through the ramifications of reversing the simplification decision that we made in `trifecta 1`. Thrashing hurts users, so it isn't a thing I'd do lightly.

**Comment by quchen** [comment]
It’s been two years since any discussion happened in here; closing as »not relevant enough to be merged«.

**Pull request closed without merging**
