### PR TITLE
Allow ansi-terminal-0.8

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Can we have release after this is merged, so changes in e5de45ff9d4ba0aca261ef54a27fdd116a2fa88f can get to Hackage

**Comment by quchen** [comment]
LGTM. I don’t think I have Hackage rights though, so @hvr has to do the release.

**Comment by phadej** [comment]
@quchen: you do 
http://hackage.haskell.org/package/ansi-wl-pprint/maintainers/

*EDIT* in fact you uploaded the last release ;)

**Comment by phadej** [comment]
ping @quchen @ekmett (you are the only maintainers of the package on Hackage, if we don't count Max). I can help with maintaining this package (i.e. bumping bounds), until it's deprecated in favor fo `prettyprinter`

**Comment by ekmett** [comment]
I've been letting @quchen manage releases lately as I don't know his long term plans.

**Comment by phadej** [comment]
@quchen weekly ping :)

**Comment by phadej** [comment]
@ekmett thanks

https://hackage.haskell.org/package/ansi-wl-pprint-0.6.8.2 uploaded

**Pull request merged**
